os: Visual Studio 2017
configuration: Release
install:
  - "SET PATH=C:\\ProgramData\\chocolatey\\bin;%PATH%"
  - choco install gitversion.portable -pre -y
  - choco install GitReleaseNotes.Portable
  - pip install codecov
before_build:
  - nuget restore
  - gitversion /l console /output buildserver
  - GitReleaseNotes . /AllTags /C breaking /O ReleaseNotes.md
build:
  project: RandomAccessPerlinNoise.sln
artifacts:
  - path: 'ReleaseNotes.md'
  - path: '**\*.nupkg'
skip_commits:
  files:
    - .gitattributes
    - .gitignore
    - CodeMaid.config
    - license.md
